src/lib-components/forms/DateRangePicker.vue

In short, this component emitted dates in the middle of the day in Unix time (which is UTC), unless the user's browser was in UTC as well, instead of the beginning & end of the day as intended.
If conversion to another timezone needs to happen, that should occur on the server-side. Otherwise, the timestamp alone does not indicate the originating timezone so some guesswork would have to occur.

dateRangePicker emits beginning & end of UTC day 

---

package.json
src/lib-components/layout/SidebarLayout.vue

The sidebar was opening links in a new tab when it should not have been. Setting `<a target="_self">` instead of `<a target=false>` resolves that.

SidebarLayout: if not item.openInTab, target='_self'

---

.github/workflows/publish.yml
dev/content/Forms.vue
dev/helpers/ComponentLayout.vue
package-lock.json
package.json
src/helpers/Uniques.ts
src/lib-components/forms/BaseInput.vue
src/lib-components/forms/Checkbox.vue
src/lib-components/forms/DateRangePicker.vue
src/lib-components/forms/InputHelp.vue
src/lib-components/forms/InputLabel.vue
src/lib-components/forms/MultiCheckboxes.vue
src/lib-components/forms/Radio.vue
src/lib-components/forms/Select.vue
src/lib-components/forms/TextArea.vue
src/lib-components/forms/YesOrNoRadio.vue
src/lib-components/index.ts
tailwind.css
trees.d.ts

- Expands on the current set of input fields.
- Includes/exposes a `<BaseInput>` component for the most common text like inputs.
- includes/exposes an `<InputLabel>` component for custom use.
- Includes/exposes an `<InputHelp>` component for custom use.
- Simplifies adding labels and help text to most input types that can support them via optional props.
- Removes the redundancy of using props for common input attributes like required and disabled by using $attrs.
- Adds basic A11y support to all current input types with no consumer configuration by using a dynamic UUID.
- Should maintain compatibility with current usage.
This is part 1 of a multi-phase plan for expanding on form fields and form handling in general.  Primary goal in this round was to expand on the current fields to make …

proposal: form field expansion

---

package-lock.json
package.json
src/lib-components/forms/Radio.vue
src/lib-components/forms/YesOrNoRadio.vue

- adds the name attribute to radio button/button groups which should fix html5 required validation issues
- bumps trees to v0.2.59
- it's not entirely clear why merging attrs with v-bind on the radio group allows for custom name attributes, but does not work similarly on the yes/no.  this is why the name attribute on yes/no radios uses an inline conditional for setting the custom or generated name attribute.

fix: missing name attribute on radio buttons

---

dev/content/Forms.vue
dev/content/Overlays.vue
package-lock.json
package.json
src/api/base.ts
src/lib-components/forms/Select.vue
src/lib-components/overlays/Slideover.vue

- fixes import.meta usage for vite support and maintains process.env support for vue-cli
- adds a default close handler to the slideover component - avoiding the need for an @click handler by the consumer
- updates the docs with slideover and toggle components 
- fixes docs typo
- adds number type support to select

proposal: v0.3.2

---

dev/content/Overlays.vue
dev/helpers/ComponentLayout.vue
dev/helpers/PropsTable.vue
package-lock.json
package.json
src/lib-components/index.ts
src/lib-components/overlays/Popover/Popover.vue
src/lib-components/overlays/Popover/PopoverContent.vue
src/lib-components/overlays/Tooltip.vue

- Implements a bare bones version of the headless ui popover.
- Provides convenience props for trigger text/icon for most commonly expected trigger use cases.
- Provides convenience text prop for simple tooltip like popovers.
- Adds positioning prop for flexible positioning.
- Keeps presentation styles minimal leaving it mostly up to the PositionContent slot to do whatever it needs.
@profsmallpine something for us to consider as we add features like this is how opinionated and convenient they should be.  Example we could strip out the triggerText and triggerIcon props and instead use those in more highly opinionated components such as "Tooltip" where the styling would be more opinionated for that specific use case.
https://user-images.githubusercontent.com/3856703/153058513-bcaf9947-486d-4 …

feat: Popover Component

---

dev/content/Overlays.vue
src/helpers/Debounce.ts
src/helpers/Throttle.ts
src/lib-components/overlays/Popover/Popover.vue
src/lib-components/overlays/Popover/PopoverContent.vue
src/lib-components/overlays/Tooltip.vue

- adds auto positioning for popovers and tooltips based on the trigger position and available viewport space
- includes position "none" option for no positioning help in popovers
- adds "as" prop to popovers and tooltips so the wrapper element can be changed easily (div vs span) is the most common use case - tooltips default to span
- basic throttle and debounce functions were added to helpers - throttle is used for auto positioning.  neither is exported to consumers yet (will consider later)
- tweaks static positioning anchor point - rather then top-left positioning on the far left of the trigger the popover flows left but anchors on the far right - this seems to be a more sensible use of space and plays nicely with wider triggers
__Basic Idea of Positioning__ - favor left to right on …

feat: popover auto position

---

dev/content/Forms.vue
dev/content/Overlays.vue
package-lock.json
package.json
src/helpers/Slots.ts
src/lib-components/forms/BaseInput.vue
src/lib-components/forms/Checkbox.vue
src/lib-components/forms/FieldsetLegend.vue
src/lib-components/forms/InputHelp.vue
src/lib-components/forms/InputLabel.vue
src/lib-components/forms/Legend.vue
src/lib-components/forms/MultiCheckboxes.vue
src/lib-components/forms/Radio.vue
src/lib-components/forms/Select.vue
src/lib-components/forms/TextArea.vue
src/lib-components/forms/Toggle.vue
src/lib-components/forms/YesOrNoRadio.vue
src/lib-components/index.ts
src/lib-components/overlays/Popover/Popover.vue

- refactor: tones down help text display to better differentiate it from labels
- fix: regression where popover wrapper was no longer wrapping trigger and content in a flexbox
- fix: two way binding issues on multicheckbox
- fix: radio, checkbox input and label positioning bug on long labels
- feat: adds help/description text support to yes/no, checkbox, multicheckbox, and radio components
- feat: adds basic legend component for style consistency
- feat: adds number type support to radio, checkbox, and multicheckbox
- feat: adds 2, 3, and 4 column multicheckbox radio button support
- feat: minimal disabled input styles for most inputs
- feat: slot based legend on multicheckbox and radio groups
- feat: disable support for multicheckbox and radio individual options
__Fix long label …

proposal: 0.4.3

---

dev/content/Composables.vue
dev/content/Home.vue
dev/serve.vue
index.html
package-lock.json
package.json
src/api/base.ts
src/composables/index.ts
src/composables/useBaseAPI.ts
src/entry.ts
src/helpers/Debounce.ts

- adds `withDelay` and `dataIntercept` options to the `RequestOptions` interface.  `withDelay` artificially delays the response from the API request for UI purposes.  `dataIntercept` is a convenience option to receive the response result that is nested inside of AxiosResponse data and server data fields
- adds type generics to BaseAPI methods so that the success response can be correctly inferred
- adds composable `useBaseAPI` which returns a handful of reactive variables that are generally useful for managing the state of a component
- adds a `debounceLeading` function for button triggered debouncing where trailing clicks should be debounced but not the initial click
- adds a composables page to the docs
- the abort feature in useBaseAPI requires an axios version bump
- …

feat: use base api

---

dev/content/Composables.vue
src/api/base.ts
src/composables/useBaseAPI.ts

- reverts extending the AxiosRequestConfig in the BaseAPI RequestConfig.  (This was easy to rationalize, but doesn't offer as much as I'd hoped aside from making the config options confusingly large.)
- allows FormData as a payload type in POST and PUT requests.    
- The FetchAPI already allows FormData in its config's body property 
- Axios handles both Objects and FormData gracefully setting the appropriate headers for you stringifying etc.  
- We don't need FormData often, but when we do we lose out on the feature set of BaseAPI and have to recreate it.
- It's technically already feasible to do this under the current BaseAPI if you do some Typescript muddlery a la `BaseAPI.post("/some-endpont", {some: "val"} as unknown as Record<string, unknown>)` - obviously shouldn't do this, but it …

revert extending AxiosRequestConfig, allow FormData payloads

---

dev/content/Forms.vue
package-lock.json
package.json
src/lib-components/forms/FieldsetLegend.vue
src/lib-components/forms/Radio.vue
src/lib-components/forms/RadioCards.vue
src/lib-components/index.ts

- adds a fancy radio button that looks like a card
- support for HTML5 form validation and FormData
- includes the benefits of headless ui features like focus trap and aria tags
- avoids using the headless ui feature of supporting FormData since their solution does not support the required attribute
- fixes layout bug in radio buttons in columns mode
- brings radio/checkbox legend styles inline with field level labels
- a potential use case in Portal.
- seems generally beneficial to have additional form field display options when the classics aren't enough
https://user-images.githubusercontent.com/3856703/174171772-503bf766-1021-4ae5-b5eb-589c535bdcc5.mov

feat: radio cards

---

README.md
config/tailwind.config.js
config/theme/colors.js
dev/content/Home.vue
dev/content/Lists.vue
dev/content/Overlays.vue
dev/content/Team.vue
dev/helpers/ComponentLayout.vue
package-lock.json
package.json
src/lib-components/forms/Toggle.vue
src/lib-components/indicators/XYSpinner.vue
src/lib-components/layout/SidebarLayout.vue
src/lib-components/layout/StackedLayout.vue
src/lib-components/navigation/Steps.vue
src/lib-components/overlays/Flash.vue
tailwind.config.js

- Updates Tailwind and the necessary dependencies for v3.  
- Avoids using most new features and is focused on removing deprecated features.
- The notable changes can be found here:  https://www.notion.so/xylabs/Notable-Tailwind-v3-Changes-1cd4734efe84497a8232dc2d3e990936

migrate to tailwind v3

---

dev/content/Overlays.vue
package-lock.json
package.json
src/lib-components/indicators/XYSpinner.vue
src/lib-components/layout/SidebarLayout.vue
src/lib-components/overlays/ContentModal.vue
src/lib-components/overlays/Flash.vue
src/lib-components/overlays/Modal.vue
src/lib-components/overlays/Slideover.vue
src/lib-components/overlays/Spinner.vue

- Resolves the issue where components like flash and spinner are visibly behind other overlay components such as slideover and modal by wrapping the spinner and flash components in the headlessui Portal component so that all overlay full viewport coverage components share the same staking context.
- Updates existing z-index values on overlay components according to each component's perceived display importance and document those new values.
- Adds a minor drop-shadow on the spinner component to increase visibility in the case of multiple full viewport overlays.
- Bump version to 0.6.1
There are situations where many layers of stacked overlay backgrounds may impact the visibility of the site negatively.  These situations should be few and can be revisited from a design language perspective …

refactor/fix: overlay stacking context and z-index values

---

src/lib-components/forms/RadioCards.vue

Opted for the regular cursor instead of `cursor-not-allowed`. Personally, not a huge fan of that cursor style and encourages someone to think something's broken or not in an expected state.

RadioCards: when disabled, has a regular cursor

---

package-lock.json
package.json
src/lib-components/forms/BaseInput.vue
src/lib-components/forms/TextArea.vue

A poor search and replace on `@update:model-value` listeners resulted in redefining emitted events from `defineEmits(["update:modelValue"])` to `defineEmits(["update:model-value"])`. The v-model directives are not applied in the later case.
The `BaseInput` and `TextArea` components appeared to be the only components affected.
I'll plan to follow this up with an eslint rule to enforce some consistency in the event names and have it error when `update:model-value` is used.  An existing optional rule in `vue/eslint`, unfortunately, considers `update:model-value` as valid and doesn't appear to be a suitable option.

fix: v-model number directive not applying on BaseInput component

---

dev/content/Overlays.vue
package-lock.json
package.json
src/lib-components/navigation/ActionsDropdown.vue
src/lib-components/overlays/Popover/Popover.vue
src/lib-components/overlays/Tooltip.vue

While reviewing #36 I noticed that there were a few runtime errors on the popover auto placement strategy from the bump to Vue 3.3, so it seemed like as good a time as any to integrate a 3rd party and solve the table actions dropdown display bug as well.
[Floating-UI](https://floating-ui.com/docs/vue) is the successor to PopperJS and has first class Vue support.  It does add a little heft to the bundle, but the trade-off seems worthwhile.

integrate floating UI's useFloating composable on Popover, Tooltip, and ActionsDropdown

---

dev/content/Forms.vue
src/composables/date.ts
src/composables/table.ts
src/lib-components/forms/DateRangePicker.vue
src/lib-components/lists/DynamicTable.vue

For naming, I went as explicit as possible on the DateRangePicker and on the DynamicTable, I wanted to keep it as close to `dateSearch` as possible so it's obvious they are related. Considered moving `dateSearch` + `dateSearchMaxRange` into a nested object on the type but this is already nested so skipped that. 
On the implementation, there are a handful of ways to approach, but using maxDate kept the component redraw in the existing logic. I am assuming that a date should be prefilled when using the range, but this could be a separate prop in the future.

Adds limit handling to DateRangePicker and pass through prop on DynamicTable

---

dev/content/Tools/UseBaseAPI.vue
package-lock.json
package.json
src/api/base.ts

- bumps axios@1.5.0
- implements axios interface changes
- set's the `paramsSerializer.indexes` option to null on the axios instance used by BaseAPI

bumps axios@1.5.0 and sets config value for params indexes

---

dev/content/Overlays.vue
src/lib-components/indicators/XYSpinner.vue
src/lib-components/lists/DynamicTable.vue

Note: There are some edge cases where multiple layers of background overlay can start to make the spinner difficult to see, but they should be minimal.  If we start to see it frequently, we can revisit.

adds branding to spinner indicator, includes inline visual on docs page

---

dev/serve.ts
package-lock.json
package.json
src/api/base.ts
src/entry.ts
vite.config.ts
vite.docs.config.ts

- refactors how the baseURL is set on the BaseAPI instance
- removes vite-environment-plugin from vite configs
- refactors vite docs and dev configs to remove needless complexity
- Setting lib vars via an ENV var doesn't play as nicely in JS module land as it does with backend code
- There's been confusion about what baseURL should be in dev vs prod like environments.  It's going to be easier mid-term for the apps to just know that `/api/v1` is the baseURL in all environments.
- With the introduction of a subdomain on portal, it's preferred that the baseURL is set without a hostname
- `process.env` is dying a slow death as a pattern generally in client side JavaScript
- It cleans up the apps Vite configs just a little more, removing an entry that is only there to prevent an error in dev …

refactor api base url configurability, cleanup vite configs

---

dev/content/Forms.vue
dev/content/Lists.vue
dev/helpers/ClickToCopy.vue
src/composables/forms.ts
src/helpers/Debounce.ts
src/index.css
src/lib-components/forms/BaseInput.vue
src/lib-components/forms/Checkbox.vue
src/lib-components/forms/DateRangePicker.vue
src/lib-components/forms/FieldsetLegend.vue
src/lib-components/forms/InputHelp.vue
src/lib-components/forms/InputLabel.vue
src/lib-components/forms/MultiCheckboxes.vue
src/lib-components/forms/Radio.vue
src/lib-components/forms/RadioCards.vue
src/lib-components/forms/Select.vue
src/lib-components/forms/TextArea.vue
src/lib-components/forms/Toggle.vue
src/lib-components/forms/YesOrNoRadio.vue
src/lib-components/lists/DynamicTable.vue

> PR 1 of 3 related to [Form Input Updates](https://www.notion.so/xylabs/8f16954aa3494675837f0cceb6a21c95?v=9d015d84f6fa48fe837c8ad0f6ab5be8&p=ecae8501d1924fa88b6561c05235759b&pm=s)
- improves form input styles (lightens borders, placeholders, labels, and help text)
- improves disabled state (sets light gray background)
- improves error state (ensures borders, placeholders, and focus state's have `classname` precedence)
- adds label and help text props to Toggle
- adds wraps all inputs in a parent div for layout consistency
- adds `useInputField` composable
- adds `error` string prop for setting error state
- removes most default placeholders (date range picker and select will continue to set a default)
- removes `legend` prop on components that used it and normalizes it to `label`
- …

1. general improvements to form input visibility, props and attrs support

---

dev/content/Forms.vue
dev/helpers/PropsTable.vue
package-lock.json
package.json
src/composables/forms.ts
src/lib-components/forms/BaseInput.vue
src/lib-components/forms/Checkbox.vue
src/lib-components/forms/DateRangePicker.vue
src/lib-components/forms/MultiCheckboxes.vue
src/lib-components/forms/Radio.vue
src/lib-components/forms/RadioCards.vue
src/lib-components/forms/Select.vue
src/lib-components/forms/TextArea.vue
src/lib-components/forms/Toggle.vue
src/lib-components/forms/YesOrNoRadio.vue

> PR 2 of 3 related to [Form Input Updates](https://www.notion.so/xylabs/8f16954aa3494675837f0cceb6a21c95?v=9d015d84f6fa48fe837c8ad0f6ab5be8&p=ecae8501d1924fa88b6561c05235759b&pm=s)
- Attempts to normalize form input props as much as possible and extracts types as needed (this is part of the broader goal of developing a form schema and simplifying new input development)
- Adds generic to `RadioCards` option type to help support type inference inside the `sublabel` slot (primarily support Portal's use case with benefits)
- Establishes that v-model is an optional prop across all inputs (this seems to be desirable from a flexibility standpoint, and as we dig further into partial updates)
- Bumps vue-tsc@latest to get generic component support
- PR 3 catches a small handful of inconsistencies …

2. extract input types, normalize props as much as possible

---

dev/content/Elements.vue
src/lib-components/forms/InputLabel.vue
src/lib-components/forms/MultiCheckboxes.vue
src/lib-components/index.ts
src/lib-components/indicators/InlineAlert.vue

- adds the `InlineAlert` component
- styling is mostly a copy/paste from the existing alert in Archive/Tailwind UI
- prop names diverge a bit from what's currently in use in Portal and Archive and does not support slots
- component API attempts to stay close to CTACard for consistency, but does diverge a bit

feature: inline alert component

---

src/lib-components/forms/TextArea.vue

- fixes lack of placeholder support in `TextArea` (moving placeholder to props means it's no longer in $attrs)
- `TextArea` help text spacing is inconsistent with other inputs

fix: textarea placeholder support and help text spacing consistency

---

dev/content/Navigation.vue
dev/content/Tools.vue
dev/content/Tools/UseUrlSearchParams.vue
src/composables/index.ts
src/composables/nav.ts

- adds `useTabHistory` for supporting tab navigation state via the browser query string: `?tab=my-tab`
- adds `useUrlSearchParams` for supporting complex search params state via the browser query string: `?q=find+me+something&q=also+this&isActive=true`
This is aimed at supporting [#1091](https://github.com/xy-planning-network/college-try/pull/1091) on Portal and establishing a common path forward for existing browser history/state support via query strings.
I ultimately landed on using a query param with `useTabHistory` since it keeps the `#` fragment free for anchors.  i.e. `/setting?tab=advisor-profile#fees`.

composables for tab history and search params history

---

src/lib-components/lists/DataTable.vue
src/lib-components/lists/DynamicTable.vue
src/lib-components/navigation/ActionsDropdown.vue

On `<DynamicTable />`...
- A column header title & sort button may not flow nicely when the title is longer. So, wrap it in a `flex` container
- Adds `bg-gray-50` on even rows to help visually differentiate
- Also removes `bg-white` from the `<ActionsDropdown />` menu icon since that may or may not mesh with the row's background color
- Fixes the default "No items found..." row length to fill in when overflowing
_Before_
_After_
https://github.com/xy-planning-network/trees/assets/27823069/da0d5854-1fe3-4278-a932-898c9972bf76

Style cleanup on tables and <ActionsDropdown />

---

dev/content/Lists.vue
src/composables/index.ts
src/composables/list.ts
src/lib-components/layout/DateFilter.vue
src/lib-components/lists/DetailList.vue

`<DetailList />` is tightly coupled to its use cases in `second-child`. A lot is baked in by default and can't be configured, unlike how `<DataTable />` and `<DynamicTable />` are more flexible and allow for more use cases.
Recently, we identified `<DetailList />` as a candidate for replacing some custom markup, simplifying the page it appears on. But the default filtering, styling, and pagination made it a bad fit.
This PR brings `<DetailList />` opens up configurability following `<DynamicTable />`'s pattern. Notably, it copies the `DynamicTableAPI`, allowing for the parent to call list resetting methods.
Next, this PR turns the date searching feature into an optional one. When turned off, the `<DetailList />` does not display with a shadowed border. The rationale there is the parent …

Open up <DetailList /> to more configuration

---

dev/pages/Indicators.vue
dev/pages/index.ts
src/lib-components/index.ts
src/lib-components/indicators/ProgressCircles.vue
src/lib-components/indicators/ProgressCirclesLabeled.vue

- adds two progress circle components for the incoming New App and Account Setup work
- adds a new docs page called "Indicators"
There's currently no expectation that these progress indicators will function like nav items and tabs, so they're pretty dumb.  The current step is indicated by the "index" of the step in "steps", i.e. step 1 is current with an index of 0.  If this doesn't feel intuitive, let me know, and we can get it changed before the first use cases.

initial progress circle components

---

dev/app.vue
src/lib-components/forms/FieldsetLegend.vue
src/lib-components/forms/InputHelp.vue
src/lib-components/forms/MultiCheckboxes.vue
src/lib-components/forms/Radio.vue
src/lib-components/forms/RadioCards.vue
src/lib-components/forms/YesOrNoRadio.vue
src/lib-components/indicators/ProgressCirclesLabeled.vue
src/lib-components/layout/SidebarLayout.vue

- Adds a slot for replacing the sidebar navigation in the `SidebarLayout` with a custom component
- tweaks some input styles to help with layout cramping
- fixes a found issue with progress circles where their height was larger than expected (helps keep it visible in a sidebar layout)
There are a lot of ways to go about replacing the navigation in the `SidebarLayout`, including having progress steps fulfill the navigation interface, but at the moment they don't function as a nav, so I took the most straightforward route to allowing the swap to occur.

SidebarLayout nav slot, form input tweaks, progress circles fix

---

dev/pages/Forms.vue
src/lib-components/forms/MultiCheckboxes.vue
src/lib-components/indicators/ProgressCirclesLabeled.vue
src/lib-components/layout/SidebarLayout.vue
vite.docs.config.ts

Makes a few improvements and fixes that have popped up recently.
- fixes progress circle sizing compared to initial design details
- fixes oversized sidebar layout header text on mobile devices - which can sometimes overflow the header
- improves Multiselect error messages when min/max are set, [see comment in #1444](https://github.com/xy-planning-network/college-try/pull/1444/files#r1745935157)
- fixes broken base path when docs build is run (causing github hosted pages to fail)
fixes DEV-2926

[DEV-2926] patch fixes and improvements 0.10.3

---

src/lib-components/forms/MultiCheckboxes.vue

A `sr-only` or "hidden" component factors is not ignored by classes like `space-x/y-*`, etc. Here's an example where the `<input>` does not exist:
Here's where it does:
This PR fixes the one case of this bug in `forms/MultiCheckboxes`. It solves it by moving the `<input />` to the end of the the `<fieldset />` that has a `space-y-6`. Here's what that looks like:
There appear to be no other components using `sr-only` where this layout bug can pop up.
If I had to explain why this is a bug - and why this PR fixes it - unfortunately, I come up a bit short.
This indicates it makes sense we're running into it: https://github.com/tailwindlabs/tailwindcss/issues/3857
But, that `<fieldset />` has a `relative` class and the `<input />` has position classes. So, my mental model suggests the `<input …

Fix: addresses `sr-only` component impacting layout

---

dev/docs/ButtonDocs.md
dev/pages/Forms.vue
package-lock.json
package.json
src/composables/forms.ts
src/entry.ts
src/index.css
src/lib-components/forms/BaseInput.vue

- adds button styles for dark/marketing like UI support [[DEV-3086]](https://www.notion.so/xylabs/8f16954aa3494675837f0cceb6a21c95?v=9d015d84f6fa48fe837c8ad0f6ab5be8&p=137d6eba0f7b8059a8b8d06d9a600c48&pm=s)
- adds basic url pattern validation to `<BaseInput type="url" />` [[DEV-2930]](https://www.notion.so/xylabs/8f16954aa3494675837f0cceb6a21c95?v=9d015d84f6fa48fe837c8ad0f6ab5be8&p=e210354a22f04dd39bbb7f96d5311a54&pm=s)
- bumps vue-tsc@latest

add url pattern validation and additional buttons

---

dev/pages/Forms.vue
package-lock.json
package.json
src/composables/forms.ts
src/entry.ts
src/lib-components/forms/NumberInput.vue
src/lib-components/index.ts

- introduces a `NumberInput` component that masks all number inputs according to US-en number formatting with support for a `money` type to handle the conversion between a monetary string input to US cents as a number
- Number handling in `BaseInput` has been good, but trying to support masking and number/money conversions for the backend is enough bloat that I'd prefer to separate them.  Longer term, it moves `BaseInput` away from supporting `number` types at all to limit type juggling on v-model values in a parent.
- Supporting a combination of prefix, precision > 0, and negative values creates some user input edge cases that can be tricky to handle.  ex: Typing a `.` character and not having it set in the input field is due to the interaction of trying to store a number type from an …

number inputs

---

dev/pages/Lists.vue
dev/pages/Navigation.vue
package-lock.json
src/composables/table.ts
src/composables/useTable.ts
src/lib-components/index.ts
src/lib-components/lists/DynamicTable.vue
src/lib-components/navigation/ActionsDropdown.vue
src/lib-components/navigation/TablePaginator.vue

- adds bulk action support on `DynamicTable`
- adds a `TablePaginator` component to replace the existing `Paginator` on tables to allow larger table views and aid in larger bulk selections
- adds `placement` support to `ActionsDropdown` - I did not end up using this, but left it for the future.
I need to find a stopping point on this one since its usage is still pretty narrow and what's here should give us something to work with for the existing use cases and some new ones.
- ~~the bulk action callback does not include the full row data, it only includes the `ids`, persistent mode makes this just a hair more difficult to add, but it's a small add when there is a little more time~~
- a unique `id` key is assumed to be on the resource record - this can be flexible in the future if needed, …

[DEV-3404] init bulk actions support on dynamic table

---

src/lib-components/forms/FieldsetLegend.vue
src/lib-components/forms/InputLabel.vue
src/lib-components/forms/RadioCards.vue

- fixes unnecessary margin on RadioCards when no copy precedes the card layout
- removes white space from required field indicators which can cause the indicator to wrap on to it's own line

[DEV-3709] minor form layout fixes

---

dev/pages/Forms.vue
src/lib-components/forms/DateRangePicker.vue

This change has the date pickers fly out menu element appended to our inputs wrapper to keep the fly out elements context within whatever other element the input is placed.  This should resolve issues where a date range picker placed in a modal or slideover is inaccessible as currently Flatpickr will append the fly out to the body and Headless UI's focus traps will prevent interaction with it.
I've added a `DateRangePicker` inside a `Slideover` in the docs for a quick test.

mount the date range picker flyout menu inside the wrapper

---

src/lib-components/lists/DetailList.vue
src/lib-components/lists/DynamicTable.vue

- sets minDate and maxDate to null when the dateRange value is 0 (unset) to avoid serializing `minDate=0&maxDate=0`
When you bring your own date range filtering to a `DynamicTable` or `DynamicList` there can be a conflict in query params where `minDate` and `maxDate` are set twice.  There are quite a few ways to think about this and deal with it, but this looks the most straightforward for now as `CommonParams` will set `MinDate/MaxDate` fields to their 0 value.  Could present some issues later if you had required date range params, but the components lack enforcement of that anyway and more would need to be done to support that.

don't seralize date range params when unset
